In [1]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [3]:
df = pd.read_csv('test_2.csv')
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

df

     delivery_location  delivery_type     length  S1  S2  S3  alarm
0               Brazil              0  31.695088   1   1   0      1
1               Brazil              1  17.997528   1   1   1      1
2               Brazil              0   4.193929   1   1   1      1
3                Spain              1   8.453601   0   0   0      0
4               Brazil              0   7.965780   1   1   1      1
...                ...            ...        ...  ..  ..  ..    ...
9995              Cuba              0   4.420658   1   1   1      1
9996             Spain              1   1.806541   1   0   0      0
9997              Cuba              0   6.378788   1   1   1      1
9998            Brazil              0   2.035510   1   1   1      1
9999             Spain              0  45.342675   0   1   1      1

[10000 rows x 7 columns]

In [4]:
model = smf.logit(formula="alarm~delivery_type", data=df)
results = model.fit(maxiter=40)
results.summary()

Optimization terminated successfully.
         Current function value: 0.604114
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  alarm   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9998
Method:                           MLE   Df Model:                            1
Date:                Mon, 22 Aug 2022   Pseudo R-squ.:                 0.01404
Time:                        15:49:19   Log-Likelihood:                -6041.1
converged:                       True   LL-Null:                       -6127.2
Covariance Type:            nonrobust   LLR p-value:                 2.643e-39
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         1.1431      0.033     34.496      0.000       1.078       1.208
delivery_type    -0.5759      0.044    -13.013      0.000      -0.663      -0.489
=================================================================================
"""

In [6]:
distance = pd.DataFrame([
    { 'delivery_type': 1 , 'intercept': 1},
    { 'delivery_type': 0, 'intercept': 1},
])


distance['predicted'] = results.predict(distance)
distance

   delivery_type  intercept  predicted
0              1          1   0.638116
1              0          1   0.758253

In [7]:
model = smf.logit(formula="alarm~delivery_type+length", data=df)
results = model.fit(maxiter=40)
results.summary()

Optimization terminated successfully.
         Current function value: 0.604047
         Iterations 5

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  alarm   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9997
Method:                           MLE   Df Model:                            2
Date:                Mon, 22 Aug 2022   Pseudo R-squ.:                 0.01415
Time:                        15:50:45   Log-Likelihood:                -6040.5
converged:                       True   LL-Null:                       -6127.2
Covariance Type:            nonrobust   LLR p-value:                 2.236e-38
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         1.1868      0.050     23.575      0.000       1.088       1.285
delivery_type    -0.5762      0.044    -13.018      0.000      -0.663      -0.489
length           -0.0017      0.002     -1.158      0.247      -0.005       0.001
=================================================================================
"""

In [17]:
content = pd.DataFrame([
    {'delivery_type': 1, 'length': 95.67952366521307},
    {'delivery_type': 0, 'length': 10},
    {'delivery_type': 1,'length': 89.86199664977082},
    {'delivery_type': 1,'length': 100},
])

content['predicted'] = results.predict(content)
content

   delivery_type      length  predicted
0              1   95.679524   0.609034
1              0   10.000000   0.763023
2              1   89.861997   0.611455
3              1  100.000000   0.607233

In [23]:
model = smf.logit(formula="S1~delivery_location", data=df)
results = model.fit(maxiter=40)
results.summary()

Optimization terminated successfully.
         Current function value: 0.458270
         Iterations 6

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                     S2   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9997
Method:                           MLE   Df Model:                            2
Date:                Mon, 22 Aug 2022   Pseudo R-squ.:                  0.1018
Time:                        15:55:44   Log-Likelihood:                -4582.7
converged:                       True   LL-Null:                       -5102.2
Covariance Type:            nonrobust   LLR p-value:                2.339e-226
==============================================================================================
                                 coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                      1.8505      0.050     36.895      0.000       1.752       1.949
delivery_location[T.Cuba]      0.4333      0.078      5.540      0.000       0.280       0.587
delivery_location[T.Spain]    -1.4253      0.061    -23.178      0.000      -1.546      -1.305
==============================================================================================
"""

In [24]:
country = pd.DataFrame([
    { 'delivery_location': 'Spain' },
    { 'delivery_location': 'Brazil' },
    { 'delivery_location': 'Cuba' },

])

country['predicted'] = results.predict(country)
country

  delivery_location  predicted
0             Spain   0.604722
1            Brazil   0.864187
2              Cuba   0.907525