In [1]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [59]:
df = pd.read_csv('test_2.csv')
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

df

     delivery_location  delivery_type     length  S1  S2  S3  alarm
0                Spain              0  41.393991   0   1   0      1
1                Spain              0  40.065522   0   0   0      0
2               Mexico              1   3.570436   0   0   0      0
3               Mexico              0  17.166233   0   1   0      1
4                 Cuba              0  11.659959   1   1   1      1
...                ...            ...        ...  ..  ..  ..    ...
9995              Cuba              0   4.645952   1   0   1      0
9996            Brazil              0  20.970650   1   0   0      1
9997            Mexico              0  24.564943   0   0   0      0
9998              Cuba              1  25.788052   1   0   0      1
9999             Spain              0   8.075789   0   0   0      0

[10000 rows x 7 columns]

In [60]:
(np.sum(df['alarm'])/10000)

0.3932

In [61]:
model = smf.logit(formula="alarm~delivery_type", data=df)
results = model.fit(maxiter=40)
results.summary()

Optimization terminated successfully.
         Current function value: 0.669617
         Iterations 4

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  alarm   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9998
Method:                           MLE   Df Model:                            1
Date:                Tue, 23 Aug 2022   Pseudo R-squ.:               0.0008072
Time:                        11:23:06   Log-Likelihood:                -6696.2
converged:                       True   LL-Null:                       -6701.6
Covariance Type:            nonrobust   LLR p-value:                  0.001005
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -0.3669      0.029    -12.741      0.000      -0.423      -0.310
delivery_type    -0.1347      0.041     -3.288      0.001      -0.215      -0.054
=================================================================================
"""

In [62]:
distance = pd.DataFrame([
    { 'delivery_type': 1 , 'intercept': 1},
    { 'delivery_type': 0, 'intercept': 1},
])


distance['predicted'] = results.predict(distance)
distance

   delivery_type  intercept  predicted
0              1          1    0.37717
1              0          1    0.40930

In [63]:
model = smf.logit(formula="alarm~delivery_type+length", data=df)
results = model.fit(maxiter=40)
results.summary()

Optimization terminated successfully.
         Current function value: 0.669040
         Iterations 4

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  alarm   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9997
Method:                           MLE   Df Model:                            2
Date:                Tue, 23 Aug 2022   Pseudo R-squ.:                0.001668
Time:                        11:23:10   Log-Likelihood:                -6690.4
converged:                       True   LL-Null:                       -6701.6
Covariance Type:            nonrobust   LLR p-value:                 1.400e-05
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -0.4893      0.046    -10.576      0.000      -0.580      -0.399
delivery_type    -0.1343      0.041     -3.277      0.001      -0.215      -0.054
length            0.0048      0.001      3.394      0.001       0.002       0.008
=================================================================================
"""

In [64]:
content = pd.DataFrame([
    {'delivery_type': 0, 'length': 95.67952366521307},
    {'delivery_type': 0, 'length': 10},
    {'delivery_type': 1,'length': 89.86199664977082},
    {'delivery_type': 1,'length': 10},
    {'delivery_type': 1,'length': 100},
])

content['predicted'] = results.predict(content)
content

   delivery_type      length  predicted
0              0   95.679524   0.493251
1              0   10.000000   0.391512
2              1   89.861997   0.452780
3              1   10.000000   0.360015
4              1  100.000000   0.464942

In [65]:
model = smf.logit(formula="S1~delivery_location", data=df)
results = model.fit(maxiter=40)
results.summary()

Optimization terminated successfully.
         Current function value: 0.569486
         Iterations 6

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                     S1   No. Observations:                10000
Model:                          Logit   Df Residuals:                     9996
Method:                           MLE   Df Model:                            3
Date:                Tue, 23 Aug 2022   Pseudo R-squ.:                  0.1780
Time:                        11:23:21   Log-Likelihood:                -5694.9
converged:                       True   LL-Null:                       -6928.4
Covariance Type:            nonrobust   LLR p-value:                     0.000
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
Intercept                       0.2068      0.040      5.196      0.000       0.129       0.285
delivery_location[T.Cuba]       1.5183      0.069     21.929      0.000       1.383       1.654
delivery_location[T.Mexico]    -0.7943      0.058    -13.753      0.000      -0.907      -0.681
delivery_location[T.Spain]     -1.5584      0.063    -24.641      0.000      -1.682      -1.434
===============================================================================================
"""

In [66]:
country = pd.DataFrame([
    { 'delivery_location': 'Spain' },
    { 'delivery_location': 'Brazil' },
    { 'delivery_location': 'Cuba' },
    { 'delivery_location': 'Mexico'}

])

country['predicted'] = results.predict(country)
country

  delivery_location  predicted
0             Spain   0.205604
1            Brazil   0.551508
2              Cuba   0.848785
3            Mexico   0.357200